/**
 * 鉴权认证微服务提供的API接口文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIAuthLogin_200_response_data.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIAuthHelpers.h"

namespace OpenAPIAuth {

OAIAuthLogin_200_response_data::OAIAuthLogin_200_response_data(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIAuthLogin_200_response_data::OAIAuthLogin_200_response_data() {
    this->initializeModel();
}

OAIAuthLogin_200_response_data::~OAIAuthLogin_200_response_data() {}

void OAIAuthLogin_200_response_data::initializeModel() {

    m_token_isSet = false;
    m_token_isValid = false;

    m_user_id_isSet = false;
    m_user_id_isValid = false;

    m_phone_isSet = false;
    m_phone_isValid = false;

    m_nickname_isSet = false;
    m_nickname_isValid = false;

    m_description_isSet = false;
    m_description_isValid = false;

    m_avatar_file_id_isSet = false;
    m_avatar_file_id_isValid = false;
}

void OAIAuthLogin_200_response_data::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIAuthLogin_200_response_data::fromJsonObject(QJsonObject json) {

    m_token_isValid = ::OpenAPIAuth::fromJsonValue(m_token, json[QString("token")]);
    m_token_isSet = !json[QString("token")].isNull() && m_token_isValid;

    m_user_id_isValid = ::OpenAPIAuth::fromJsonValue(m_user_id, json[QString("userId")]);
    m_user_id_isSet = !json[QString("userId")].isNull() && m_user_id_isValid;

    m_phone_isValid = ::OpenAPIAuth::fromJsonValue(m_phone, json[QString("phone")]);
    m_phone_isSet = !json[QString("phone")].isNull() && m_phone_isValid;

    m_nickname_isValid = ::OpenAPIAuth::fromJsonValue(m_nickname, json[QString("nickname")]);
    m_nickname_isSet = !json[QString("nickname")].isNull() && m_nickname_isValid;

    m_description_isValid = ::OpenAPIAuth::fromJsonValue(m_description, json[QString("description")]);
    m_description_isSet = !json[QString("description")].isNull() && m_description_isValid;

    m_avatar_file_id_isValid = ::OpenAPIAuth::fromJsonValue(m_avatar_file_id, json[QString("avatarFileId")]);
    m_avatar_file_id_isSet = !json[QString("avatarFileId")].isNull() && m_avatar_file_id_isValid;
}

QString OAIAuthLogin_200_response_data::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIAuthLogin_200_response_data::asJsonObject() const {
    QJsonObject obj;
    if (m_token_isSet) {
        obj.insert(QString("token"), ::OpenAPIAuth::toJsonValue(m_token));
    }
    if (m_user_id_isSet) {
        obj.insert(QString("userId"), ::OpenAPIAuth::toJsonValue(m_user_id));
    }
    if (m_phone_isSet) {
        obj.insert(QString("phone"), ::OpenAPIAuth::toJsonValue(m_phone));
    }
    if (m_nickname_isSet) {
        obj.insert(QString("nickname"), ::OpenAPIAuth::toJsonValue(m_nickname));
    }
    if (m_description_isSet) {
        obj.insert(QString("description"), ::OpenAPIAuth::toJsonValue(m_description));
    }
    if (m_avatar_file_id_isSet) {
        obj.insert(QString("avatarFileId"), ::OpenAPIAuth::toJsonValue(m_avatar_file_id));
    }
    return obj;
}

QString OAIAuthLogin_200_response_data::getToken() const {
    return m_token;
}
void OAIAuthLogin_200_response_data::setToken(const QString &token) {
    m_token = token;
    m_token_isSet = true;
}

bool OAIAuthLogin_200_response_data::is_token_Set() const{
    return m_token_isSet;
}

bool OAIAuthLogin_200_response_data::is_token_Valid() const{
    return m_token_isValid;
}

QString OAIAuthLogin_200_response_data::getUserId() const {
    return m_user_id;
}
void OAIAuthLogin_200_response_data::setUserId(const QString &user_id) {
    m_user_id = user_id;
    m_user_id_isSet = true;
}

bool OAIAuthLogin_200_response_data::is_user_id_Set() const{
    return m_user_id_isSet;
}

bool OAIAuthLogin_200_response_data::is_user_id_Valid() const{
    return m_user_id_isValid;
}

QString OAIAuthLogin_200_response_data::getPhone() const {
    return m_phone;
}
void OAIAuthLogin_200_response_data::setPhone(const QString &phone) {
    m_phone = phone;
    m_phone_isSet = true;
}

bool OAIAuthLogin_200_response_data::is_phone_Set() const{
    return m_phone_isSet;
}

bool OAIAuthLogin_200_response_data::is_phone_Valid() const{
    return m_phone_isValid;
}

QString OAIAuthLogin_200_response_data::getNickname() const {
    return m_nickname;
}
void OAIAuthLogin_200_response_data::setNickname(const QString &nickname) {
    m_nickname = nickname;
    m_nickname_isSet = true;
}

bool OAIAuthLogin_200_response_data::is_nickname_Set() const{
    return m_nickname_isSet;
}

bool OAIAuthLogin_200_response_data::is_nickname_Valid() const{
    return m_nickname_isValid;
}

QString OAIAuthLogin_200_response_data::getDescription() const {
    return m_description;
}
void OAIAuthLogin_200_response_data::setDescription(const QString &description) {
    m_description = description;
    m_description_isSet = true;
}

bool OAIAuthLogin_200_response_data::is_description_Set() const{
    return m_description_isSet;
}

bool OAIAuthLogin_200_response_data::is_description_Valid() const{
    return m_description_isValid;
}

QString OAIAuthLogin_200_response_data::getAvatarFileId() const {
    return m_avatar_file_id;
}
void OAIAuthLogin_200_response_data::setAvatarFileId(const QString &avatar_file_id) {
    m_avatar_file_id = avatar_file_id;
    m_avatar_file_id_isSet = true;
}

bool OAIAuthLogin_200_response_data::is_avatar_file_id_Set() const{
    return m_avatar_file_id_isSet;
}

bool OAIAuthLogin_200_response_data::is_avatar_file_id_Valid() const{
    return m_avatar_file_id_isValid;
}

bool OAIAuthLogin_200_response_data::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_token_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_user_id_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_phone_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_nickname_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_description_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_avatar_file_id_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIAuthLogin_200_response_data::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_token_isValid && m_user_id_isValid && m_phone_isValid && m_nickname_isValid && m_description_isValid && m_avatar_file_id_isValid && true;
}

} // namespace OpenAPIAuth
