/**
 * 鉴权认证微服务提供的API接口文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#ifndef OAIAuth_ENUM_H
#define OAIAuth_ENUM_H

#include <QJsonValue>
#include <QMetaType>
#include <QString>

namespace OpenAPIAuth {

class OAIAuthEnum {
public:
    OAIAuthEnum() {}

    OAIAuthEnum(QString jsonString) {
        fromJson(jsonString);
    }

    virtual ~OAIAuthEnum() {}

    virtual QJsonValue asJsonValue() const {
        return QJsonValue(jstr);
    }

    virtual QString asJson() const {
        return jstr;
    }

    virtual void fromJson(QString jsonString) {
        jstr = jsonString;
    }

    virtual void fromJsonValue(QJsonValue jval) {
        jstr = jval.toString();
    }

    virtual bool isSet() const {
        return false;
    }

    virtual bool isValid() const {
        return true;
    }

private:
    QString jstr;
};

} // namespace OpenAPIAuth

Q_DECLARE_METATYPE(OpenAPIAuth::OAIAuthEnum)

#endif // OAIAuth_ENUM_H
