/**
 * 鉴权认证微服务提供的API接口文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIAuthLogin_request.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIAuthHelpers.h"

namespace OpenAPIAuth {

OAIAuthLogin_request::OAIAuthLogin_request(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIAuthLogin_request::OAIAuthLogin_request() {
    this->initializeModel();
}

OAIAuthLogin_request::~OAIAuthLogin_request() {}

void OAIAuthLogin_request::initializeModel() {

    m_account_isSet = false;
    m_account_isValid = false;

    m_password_isSet = false;
    m_password_isValid = false;
}

void OAIAuthLogin_request::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIAuthLogin_request::fromJsonObject(QJsonObject json) {

    m_account_isValid = ::OpenAPIAuth::fromJsonValue(m_account, json[QString("account")]);
    m_account_isSet = !json[QString("account")].isNull() && m_account_isValid;

    m_password_isValid = ::OpenAPIAuth::fromJsonValue(m_password, json[QString("password")]);
    m_password_isSet = !json[QString("password")].isNull() && m_password_isValid;
}

QString OAIAuthLogin_request::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIAuthLogin_request::asJsonObject() const {
    QJsonObject obj;
    if (m_account_isSet) {
        obj.insert(QString("account"), ::OpenAPIAuth::toJsonValue(m_account));
    }
    if (m_password_isSet) {
        obj.insert(QString("password"), ::OpenAPIAuth::toJsonValue(m_password));
    }
    return obj;
}

QString OAIAuthLogin_request::getAccount() const {
    return m_account;
}
void OAIAuthLogin_request::setAccount(const QString &account) {
    m_account = account;
    m_account_isSet = true;
}

bool OAIAuthLogin_request::is_account_Set() const{
    return m_account_isSet;
}

bool OAIAuthLogin_request::is_account_Valid() const{
    return m_account_isValid;
}

QString OAIAuthLogin_request::getPassword() const {
    return m_password;
}
void OAIAuthLogin_request::setPassword(const QString &password) {
    m_password = password;
    m_password_isSet = true;
}

bool OAIAuthLogin_request::is_password_Set() const{
    return m_password_isSet;
}

bool OAIAuthLogin_request::is_password_Valid() const{
    return m_password_isValid;
}

bool OAIAuthLogin_request::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_account_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_password_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIAuthLogin_request::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_account_isValid && m_password_isValid && true;
}

} // namespace OpenAPIAuth
