/**
 * 鉴权认证微服务提供的API接口文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIAuthLogin_200_response_data.h
 *
 * 
 */

#ifndef OAIAuthLogin_200_response_data_H
#define OAIAuthLogin_200_response_data_H

#include <QJsonObject>

#include <QString>

#include "OAIAuthEnum.h"
#include "OAIAuthObject.h"

namespace OpenAPIAuth {

class OAIAuthLogin_200_response_data : public OAIAuthObject {
public:
    OAIAuthLogin_200_response_data();
    OAIAuthLogin_200_response_data(QString json);
    ~OAIAuthLogin_200_response_data() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getToken() const;
    void setToken(const QString &token);
    bool is_token_Set() const;
    bool is_token_Valid() const;

    QString getUserId() const;
    void setUserId(const QString &user_id);
    bool is_user_id_Set() const;
    bool is_user_id_Valid() const;

    QString getPhone() const;
    void setPhone(const QString &phone);
    bool is_phone_Set() const;
    bool is_phone_Valid() const;

    QString getNickname() const;
    void setNickname(const QString &nickname);
    bool is_nickname_Set() const;
    bool is_nickname_Valid() const;

    QString getDescription() const;
    void setDescription(const QString &description);
    bool is_description_Set() const;
    bool is_description_Valid() const;

    QString getAvatarFileId() const;
    void setAvatarFileId(const QString &avatar_file_id);
    bool is_avatar_file_id_Set() const;
    bool is_avatar_file_id_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString m_token;
    bool m_token_isSet;
    bool m_token_isValid;

    QString m_user_id;
    bool m_user_id_isSet;
    bool m_user_id_isValid;

    QString m_phone;
    bool m_phone_isSet;
    bool m_phone_isValid;

    QString m_nickname;
    bool m_nickname_isSet;
    bool m_nickname_isValid;

    QString m_description;
    bool m_description_isSet;
    bool m_description_isValid;

    QString m_avatar_file_id;
    bool m_avatar_file_id_isSet;
    bool m_avatar_file_id_isValid;
};

} // namespace OpenAPIAuth

Q_DECLARE_METATYPE(OpenAPIAuth::OAIAuthLogin_200_response_data)

#endif // OAIAuthLogin_200_response_data_H
