/**
 * 鉴权认证微服务提供的API接口文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIAuthLogin_request.h
 *
 * 
 */

#ifndef OAIAuthLogin_request_H
#define OAIAuthLogin_request_H

#include <QJsonObject>

#include <QString>

#include "OAIAuthEnum.h"
#include "OAIAuthObject.h"

namespace OpenAPIAuth {

class OAIAuthLogin_request : public OAIAuthObject {
public:
    OAIAuthLogin_request();
    OAIAuthLogin_request(QString json);
    ~OAIAuthLogin_request() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getAccount() const;
    void setAccount(const QString &account);
    bool is_account_Set() const;
    bool is_account_Valid() const;

    QString getPassword() const;
    void setPassword(const QString &password);
    bool is_password_Set() const;
    bool is_password_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString m_account;
    bool m_account_isSet;
    bool m_account_isValid;

    QString m_password;
    bool m_password_isSet;
    bool m_password_isValid;
};

} // namespace OpenAPIAuth

Q_DECLARE_METATYPE(OpenAPIAuth::OAIAuthLogin_request)

#endif // OAIAuthLogin_request_H
