/**
 * 鉴权认证微服务提供的API接口文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#ifndef OAIAuth_OAIAuthDefaultApi_H
#define OAIAuth_OAIAuthDefaultApi_H

#include "OAIAuthHelpers.h"
#include "OAIAuthHttpRequest.h"
#include "OAIAuthServerConfiguration.h"
#include "OAIAuthOauth.h"

#include "OAIAuthLogin_200_response.h"
#include "OAIAuthLogin_request.h"
#include <QString>

#include <QObject>
#include <QByteArray>
#include <QStringList>
#include <QList>
#include <QNetworkAccessManager>

namespace OpenAPIAuth {

class OAIAuthDefaultApi : public QObject {
    Q_OBJECT

public:
    OAIAuthDefaultApi(const int timeOut = 0);
    ~OAIAuthDefaultApi();

    void initializeServerConfigs();
    int setDefaultServerValue(int serverIndex,const QString &operation, const QString &variable,const QString &val);
    void setServerIndex(const QString &operation, int serverIndex);
    void setApiKey(const QString &apiKeyName, const QString &apiKey);
    void setBearerToken(const QString &token);
    void setUsername(const QString &username);
    void setPassword(const QString &password);
    void setTimeOut(const int timeOut);
    void setWorkingDirectory(const QString &path);
    void setNetworkAccessManager(QNetworkAccessManager* manager);
    int addServerConfiguration(const QString &operation, const QUrl &url, const QString &description = "", const QMap<QString, OAIAuthServerVariable> &variables = QMap<QString, OAIAuthServerVariable>());
    void setNewServerForAllOperations(const QUrl &url, const QString &description = "", const QMap<QString, OAIAuthServerVariable> &variables =  QMap<QString, OAIAuthServerVariable>());
    void setNewServer(const QString &operation, const QUrl &url, const QString &description = "", const QMap<QString, OAIAuthServerVariable> &variables =  QMap<QString, OAIAuthServerVariable>());
    void addHeaders(const QString &key, const QString &value);
    void enableRequestCompression();
    void enableResponseCompression();
    void abortRequests();
    QString getParamStylePrefix(const QString &style);
    QString getParamStyleSuffix(const QString &style);
    QString getParamStyleDelimiter(const QString &style, const QString &name, bool isExplode);

    /**
    * @param[in]  oai_auth_login_request OAIAuthLogin_request [required]
    */
    void login(const OAIAuthLogin_request &oai_auth_login_request);


private:
    QMap<QString,int> _serverIndices;
    QMap<QString,QList<OAIAuthServerConfiguration>> _serverConfigs;
    QMap<QString, QString> _apiKeys;
    QString _bearerToken;
    QString _username;
    QString _password;
    int _timeOut;
    QString _workingDirectory;
    QNetworkAccessManager* _manager;
    QMap<QString, QString> _defaultHeaders;
    bool _isResponseCompressionEnabled;
    bool _isRequestCompressionEnabled;
    OAIAuthHttpRequestInput _latestInput;
    OAIAuthHttpRequestWorker *_latestWorker;
    QStringList _latestScope;
    OauthCode _authFlow;
    OauthImplicit _implicitFlow;
    OauthCredentials _credentialFlow;
    OauthPassword _passwordFlow;
    int _OauthMethod = 0;

    void loginCallback(OAIAuthHttpRequestWorker *worker);

Q_SIGNALS:

    void loginSignal(OAIAuthLogin_200_response summary);

    void loginSignalFull(OAIAuthHttpRequestWorker *worker, OAIAuthLogin_200_response summary);

    Q_DECL_DEPRECATED_X("Use loginSignalError() instead")
    void loginSignalE(OAIAuthLogin_200_response summary, QNetworkReply::NetworkError error_type, QString error_str);
    void loginSignalError(OAIAuthLogin_200_response summary, QNetworkReply::NetworkError error_type, const QString &error_str);

    Q_DECL_DEPRECATED_X("Use loginSignalErrorFull() instead")
    void loginSignalEFull(OAIAuthHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void loginSignalErrorFull(OAIAuthHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);

    void abortRequestsSignal();
    void allPendingRequestsCompleted();

public Q_SLOTS:
    void tokenAvailable();
};

} // namespace OpenAPIAuth
#endif
