/**
 * 聊天微服务提供的API接口文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIChatSendTextMessage_200_response_data.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIChatHelpers.h"

namespace OpenAPIChat {

OAIChatSendTextMessage_200_response_data::OAIChatSendTextMessage_200_response_data(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIChatSendTextMessage_200_response_data::OAIChatSendTextMessage_200_response_data() {
    this->initializeModel();
}

OAIChatSendTextMessage_200_response_data::~OAIChatSendTextMessage_200_response_data() {}

void OAIChatSendTextMessage_200_response_data::initializeModel() {

    m_message_id_isSet = false;
    m_message_id_isValid = false;

    m_sequence_isSet = false;
    m_sequence_isValid = false;

    m_send_time_isSet = false;
    m_send_time_isValid = false;
}

void OAIChatSendTextMessage_200_response_data::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIChatSendTextMessage_200_response_data::fromJsonObject(QJsonObject json) {

    m_message_id_isValid = ::OpenAPIChat::fromJsonValue(m_message_id, json[QString("messageId")]);
    m_message_id_isSet = !json[QString("messageId")].isNull() && m_message_id_isValid;

    m_sequence_isValid = ::OpenAPIChat::fromJsonValue(m_sequence, json[QString("sequence")]);
    m_sequence_isSet = !json[QString("sequence")].isNull() && m_sequence_isValid;

    m_send_time_isValid = ::OpenAPIChat::fromJsonValue(m_send_time, json[QString("sendTime")]);
    m_send_time_isSet = !json[QString("sendTime")].isNull() && m_send_time_isValid;
}

QString OAIChatSendTextMessage_200_response_data::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIChatSendTextMessage_200_response_data::asJsonObject() const {
    QJsonObject obj;
    if (m_message_id_isSet) {
        obj.insert(QString("messageId"), ::OpenAPIChat::toJsonValue(m_message_id));
    }
    if (m_sequence_isSet) {
        obj.insert(QString("sequence"), ::OpenAPIChat::toJsonValue(m_sequence));
    }
    if (m_send_time_isSet) {
        obj.insert(QString("sendTime"), ::OpenAPIChat::toJsonValue(m_send_time));
    }
    return obj;
}

QString OAIChatSendTextMessage_200_response_data::getMessageId() const {
    return m_message_id;
}
void OAIChatSendTextMessage_200_response_data::setMessageId(const QString &message_id) {
    m_message_id = message_id;
    m_message_id_isSet = true;
}

bool OAIChatSendTextMessage_200_response_data::is_message_id_Set() const{
    return m_message_id_isSet;
}

bool OAIChatSendTextMessage_200_response_data::is_message_id_Valid() const{
    return m_message_id_isValid;
}

qint64 OAIChatSendTextMessage_200_response_data::getSequence() const {
    return m_sequence;
}
void OAIChatSendTextMessage_200_response_data::setSequence(const qint64 &sequence) {
    m_sequence = sequence;
    m_sequence_isSet = true;
}

bool OAIChatSendTextMessage_200_response_data::is_sequence_Set() const{
    return m_sequence_isSet;
}

bool OAIChatSendTextMessage_200_response_data::is_sequence_Valid() const{
    return m_sequence_isValid;
}

QDateTime OAIChatSendTextMessage_200_response_data::getSendTime() const {
    return m_send_time;
}
void OAIChatSendTextMessage_200_response_data::setSendTime(const QDateTime &send_time) {
    m_send_time = send_time;
    m_send_time_isSet = true;
}

bool OAIChatSendTextMessage_200_response_data::is_send_time_Set() const{
    return m_send_time_isSet;
}

bool OAIChatSendTextMessage_200_response_data::is_send_time_Valid() const{
    return m_send_time_isValid;
}

bool OAIChatSendTextMessage_200_response_data::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_message_id_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_sequence_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_send_time_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIChatSendTextMessage_200_response_data::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_message_id_isValid && m_sequence_isValid && m_send_time_isValid && true;
}

} // namespace OpenAPIChat
