/**
 * 聊天微服务提供的API接口文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIChatAcceptFriendApplication_request.h
 *
 * 
 */

#ifndef OAIChatAcceptFriendApplication_request_H
#define OAIChatAcceptFriendApplication_request_H

#include <QJsonObject>

#include <QString>

#include "OAIChatEnum.h"
#include "OAIChatObject.h"

namespace OpenAPIChat {

class OAIChatAcceptFriendApplication_request : public OAIChatObject {
public:
    OAIChatAcceptFriendApplication_request();
    OAIChatAcceptFriendApplication_request(QString json);
    ~OAIChatAcceptFriendApplication_request() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getRecipientRemark() const;
    void setRecipientRemark(const QString &recipient_remark);
    bool is_recipient_remark_Set() const;
    bool is_recipient_remark_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString m_recipient_remark;
    bool m_recipient_remark_isSet;
    bool m_recipient_remark_isValid;
};

} // namespace OpenAPIChat

Q_DECLARE_METATYPE(OpenAPIChat::OAIChatAcceptFriendApplication_request)

#endif // OAIChatAcceptFriendApplication_request_H
