/**
 * 聊天微服务提供的API接口文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIChatSendTextMessage_200_response.h
 *
 * 
 */

#ifndef OAIChatSendTextMessage_200_response_H
#define OAIChatSendTextMessage_200_response_H

#include <QJsonObject>

#include "OAIChatSendTextMessage_200_response_data.h"
#include <QString>

#include "OAIChatEnum.h"
#include "OAIChatObject.h"

namespace OpenAPIChat {
class OAIChatSendTextMessage_200_response_data;

class OAIChatSendTextMessage_200_response : public OAIChatObject {
public:
    OAIChatSendTextMessage_200_response();
    OAIChatSendTextMessage_200_response(QString json);
    ~OAIChatSendTextMessage_200_response() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    bool isSuccess() const;
    void setSuccess(const bool &success);
    bool is_success_Set() const;
    bool is_success_Valid() const;

    OAIChatSendTextMessage_200_response_data getData() const;
    void setData(const OAIChatSendTextMessage_200_response_data &data);
    bool is_data_Set() const;
    bool is_data_Valid() const;

    QString getErrCode() const;
    void setErrCode(const QString &err_code);
    bool is_err_code_Set() const;
    bool is_err_code_Valid() const;

    QString getErrMsg() const;
    void setErrMsg(const QString &err_msg);
    bool is_err_msg_Set() const;
    bool is_err_msg_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    bool m_success;
    bool m_success_isSet;
    bool m_success_isValid;

    OAIChatSendTextMessage_200_response_data m_data;
    bool m_data_isSet;
    bool m_data_isValid;

    QString m_err_code;
    bool m_err_code_isSet;
    bool m_err_code_isValid;

    QString m_err_msg;
    bool m_err_msg_isSet;
    bool m_err_msg_isValid;
};

} // namespace OpenAPIChat

Q_DECLARE_METATYPE(OpenAPIChat::OAIChatSendTextMessage_200_response)

#endif // OAIChatSendTextMessage_200_response_H
