/**
 * 聊天微服务提供的API接口文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIChatRejectFriendApplication_200_response.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIChatHelpers.h"

namespace OpenAPIChat {

OAIChatRejectFriendApplication_200_response::OAIChatRejectFriendApplication_200_response(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIChatRejectFriendApplication_200_response::OAIChatRejectFriendApplication_200_response() {
    this->initializeModel();
}

OAIChatRejectFriendApplication_200_response::~OAIChatRejectFriendApplication_200_response() {}

void OAIChatRejectFriendApplication_200_response::initializeModel() {

    m_success_isSet = false;
    m_success_isValid = false;

    m_err_code_isSet = false;
    m_err_code_isValid = false;

    m_err_msg_isSet = false;
    m_err_msg_isValid = false;
}

void OAIChatRejectFriendApplication_200_response::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIChatRejectFriendApplication_200_response::fromJsonObject(QJsonObject json) {

    m_success_isValid = ::OpenAPIChat::fromJsonValue(m_success, json[QString("success")]);
    m_success_isSet = !json[QString("success")].isNull() && m_success_isValid;

    m_err_code_isValid = ::OpenAPIChat::fromJsonValue(m_err_code, json[QString("errCode")]);
    m_err_code_isSet = !json[QString("errCode")].isNull() && m_err_code_isValid;

    m_err_msg_isValid = ::OpenAPIChat::fromJsonValue(m_err_msg, json[QString("errMsg")]);
    m_err_msg_isSet = !json[QString("errMsg")].isNull() && m_err_msg_isValid;
}

QString OAIChatRejectFriendApplication_200_response::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIChatRejectFriendApplication_200_response::asJsonObject() const {
    QJsonObject obj;
    if (m_success_isSet) {
        obj.insert(QString("success"), ::OpenAPIChat::toJsonValue(m_success));
    }
    if (m_err_code_isSet) {
        obj.insert(QString("errCode"), ::OpenAPIChat::toJsonValue(m_err_code));
    }
    if (m_err_msg_isSet) {
        obj.insert(QString("errMsg"), ::OpenAPIChat::toJsonValue(m_err_msg));
    }
    return obj;
}

bool OAIChatRejectFriendApplication_200_response::isSuccess() const {
    return m_success;
}
void OAIChatRejectFriendApplication_200_response::setSuccess(const bool &success) {
    m_success = success;
    m_success_isSet = true;
}

bool OAIChatRejectFriendApplication_200_response::is_success_Set() const{
    return m_success_isSet;
}

bool OAIChatRejectFriendApplication_200_response::is_success_Valid() const{
    return m_success_isValid;
}

QString OAIChatRejectFriendApplication_200_response::getErrCode() const {
    return m_err_code;
}
void OAIChatRejectFriendApplication_200_response::setErrCode(const QString &err_code) {
    m_err_code = err_code;
    m_err_code_isSet = true;
}

bool OAIChatRejectFriendApplication_200_response::is_err_code_Set() const{
    return m_err_code_isSet;
}

bool OAIChatRejectFriendApplication_200_response::is_err_code_Valid() const{
    return m_err_code_isValid;
}

QString OAIChatRejectFriendApplication_200_response::getErrMsg() const {
    return m_err_msg;
}
void OAIChatRejectFriendApplication_200_response::setErrMsg(const QString &err_msg) {
    m_err_msg = err_msg;
    m_err_msg_isSet = true;
}

bool OAIChatRejectFriendApplication_200_response::is_err_msg_Set() const{
    return m_err_msg_isSet;
}

bool OAIChatRejectFriendApplication_200_response::is_err_msg_Valid() const{
    return m_err_msg_isValid;
}

bool OAIChatRejectFriendApplication_200_response::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_success_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_err_code_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_err_msg_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIChatRejectFriendApplication_200_response::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_success_isValid && true;
}

} // namespace OpenAPIChat
