/**
 * 聊天微服务提供的API接口文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIChatAcceptFriendApplication_request.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIChatHelpers.h"

namespace OpenAPIChat {

OAIChatAcceptFriendApplication_request::OAIChatAcceptFriendApplication_request(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIChatAcceptFriendApplication_request::OAIChatAcceptFriendApplication_request() {
    this->initializeModel();
}

OAIChatAcceptFriendApplication_request::~OAIChatAcceptFriendApplication_request() {}

void OAIChatAcceptFriendApplication_request::initializeModel() {

    m_recipient_remark_isSet = false;
    m_recipient_remark_isValid = false;
}

void OAIChatAcceptFriendApplication_request::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIChatAcceptFriendApplication_request::fromJsonObject(QJsonObject json) {

    m_recipient_remark_isValid = ::OpenAPIChat::fromJsonValue(m_recipient_remark, json[QString("recipientRemark")]);
    m_recipient_remark_isSet = !json[QString("recipientRemark")].isNull() && m_recipient_remark_isValid;
}

QString OAIChatAcceptFriendApplication_request::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIChatAcceptFriendApplication_request::asJsonObject() const {
    QJsonObject obj;
    if (m_recipient_remark_isSet) {
        obj.insert(QString("recipientRemark"), ::OpenAPIChat::toJsonValue(m_recipient_remark));
    }
    return obj;
}

QString OAIChatAcceptFriendApplication_request::getRecipientRemark() const {
    return m_recipient_remark;
}
void OAIChatAcceptFriendApplication_request::setRecipientRemark(const QString &recipient_remark) {
    m_recipient_remark = recipient_remark;
    m_recipient_remark_isSet = true;
}

bool OAIChatAcceptFriendApplication_request::is_recipient_remark_Set() const{
    return m_recipient_remark_isSet;
}

bool OAIChatAcceptFriendApplication_request::is_recipient_remark_Valid() const{
    return m_recipient_remark_isValid;
}

bool OAIChatAcceptFriendApplication_request::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_recipient_remark_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIChatAcceptFriendApplication_request::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_recipient_remark_isValid && true;
}

} // namespace OpenAPIChat
