/**
 * 聊天微服务提供的API接口文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIChatSendFriendApplication_200_response_data.h
 *
 * 
 */

#ifndef OAIChatSendFriendApplication_200_response_data_H
#define OAIChatSendFriendApplication_200_response_data_H

#include <QJsonObject>

#include <QString>

#include "OAIChatEnum.h"
#include "OAIChatObject.h"

namespace OpenAPIChat {

class OAIChatSendFriendApplication_200_response_data : public OAIChatObject {
public:
    OAIChatSendFriendApplication_200_response_data();
    OAIChatSendFriendApplication_200_response_data(QString json);
    ~OAIChatSendFriendApplication_200_response_data() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getFriendApplicationId() const;
    void setFriendApplicationId(const QString &friend_application_id);
    bool is_friend_application_id_Set() const;
    bool is_friend_application_id_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString m_friend_application_id;
    bool m_friend_application_id_isSet;
    bool m_friend_application_id_isValid;
};

} // namespace OpenAPIChat

Q_DECLARE_METATYPE(OpenAPIChat::OAIChatSendFriendApplication_200_response_data)

#endif // OAIChatSendFriendApplication_200_response_data_H
