/**
 * 聊天微服务提供的API接口文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIChatSendTextMessage_request.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIChatHelpers.h"

namespace OpenAPIChat {

OAIChatSendTextMessage_request::OAIChatSendTextMessage_request(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIChatSendTextMessage_request::OAIChatSendTextMessage_request() {
    this->initializeModel();
}

OAIChatSendTextMessage_request::~OAIChatSendTextMessage_request() {}

void OAIChatSendTextMessage_request::initializeModel() {

    m_content_isSet = false;
    m_content_isValid = false;
}

void OAIChatSendTextMessage_request::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIChatSendTextMessage_request::fromJsonObject(QJsonObject json) {

    m_content_isValid = ::OpenAPIChat::fromJsonValue(m_content, json[QString("content")]);
    m_content_isSet = !json[QString("content")].isNull() && m_content_isValid;
}

QString OAIChatSendTextMessage_request::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIChatSendTextMessage_request::asJsonObject() const {
    QJsonObject obj;
    if (m_content_isSet) {
        obj.insert(QString("content"), ::OpenAPIChat::toJsonValue(m_content));
    }
    return obj;
}

QString OAIChatSendTextMessage_request::getContent() const {
    return m_content;
}
void OAIChatSendTextMessage_request::setContent(const QString &content) {
    m_content = content;
    m_content_isSet = true;
}

bool OAIChatSendTextMessage_request::is_content_Set() const{
    return m_content_isSet;
}

bool OAIChatSendTextMessage_request::is_content_Valid() const{
    return m_content_isValid;
}

bool OAIChatSendTextMessage_request::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_content_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIChatSendTextMessage_request::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_content_isValid && true;
}

} // namespace OpenAPIChat
