/**
 * 聊天微服务提供的API接口文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIChatSendFriendApplication_request.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIChatHelpers.h"

namespace OpenAPIChat {

OAIChatSendFriendApplication_request::OAIChatSendFriendApplication_request(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIChatSendFriendApplication_request::OAIChatSendFriendApplication_request() {
    this->initializeModel();
}

OAIChatSendFriendApplication_request::~OAIChatSendFriendApplication_request() {}

void OAIChatSendFriendApplication_request::initializeModel() {

    m_target_user_id_isSet = false;
    m_target_user_id_isValid = false;

    m_verification_message_isSet = false;
    m_verification_message_isValid = false;

    m_recipient_remark_isSet = false;
    m_recipient_remark_isValid = false;
}

void OAIChatSendFriendApplication_request::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIChatSendFriendApplication_request::fromJsonObject(QJsonObject json) {

    m_target_user_id_isValid = ::OpenAPIChat::fromJsonValue(m_target_user_id, json[QString("targetUserId")]);
    m_target_user_id_isSet = !json[QString("targetUserId")].isNull() && m_target_user_id_isValid;

    m_verification_message_isValid = ::OpenAPIChat::fromJsonValue(m_verification_message, json[QString("verificationMessage")]);
    m_verification_message_isSet = !json[QString("verificationMessage")].isNull() && m_verification_message_isValid;

    m_recipient_remark_isValid = ::OpenAPIChat::fromJsonValue(m_recipient_remark, json[QString("recipientRemark")]);
    m_recipient_remark_isSet = !json[QString("recipientRemark")].isNull() && m_recipient_remark_isValid;
}

QString OAIChatSendFriendApplication_request::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIChatSendFriendApplication_request::asJsonObject() const {
    QJsonObject obj;
    if (m_target_user_id_isSet) {
        obj.insert(QString("targetUserId"), ::OpenAPIChat::toJsonValue(m_target_user_id));
    }
    if (m_verification_message_isSet) {
        obj.insert(QString("verificationMessage"), ::OpenAPIChat::toJsonValue(m_verification_message));
    }
    if (m_recipient_remark_isSet) {
        obj.insert(QString("recipientRemark"), ::OpenAPIChat::toJsonValue(m_recipient_remark));
    }
    return obj;
}

QString OAIChatSendFriendApplication_request::getTargetUserId() const {
    return m_target_user_id;
}
void OAIChatSendFriendApplication_request::setTargetUserId(const QString &target_user_id) {
    m_target_user_id = target_user_id;
    m_target_user_id_isSet = true;
}

bool OAIChatSendFriendApplication_request::is_target_user_id_Set() const{
    return m_target_user_id_isSet;
}

bool OAIChatSendFriendApplication_request::is_target_user_id_Valid() const{
    return m_target_user_id_isValid;
}

QString OAIChatSendFriendApplication_request::getVerificationMessage() const {
    return m_verification_message;
}
void OAIChatSendFriendApplication_request::setVerificationMessage(const QString &verification_message) {
    m_verification_message = verification_message;
    m_verification_message_isSet = true;
}

bool OAIChatSendFriendApplication_request::is_verification_message_Set() const{
    return m_verification_message_isSet;
}

bool OAIChatSendFriendApplication_request::is_verification_message_Valid() const{
    return m_verification_message_isValid;
}

QString OAIChatSendFriendApplication_request::getRecipientRemark() const {
    return m_recipient_remark;
}
void OAIChatSendFriendApplication_request::setRecipientRemark(const QString &recipient_remark) {
    m_recipient_remark = recipient_remark;
    m_recipient_remark_isSet = true;
}

bool OAIChatSendFriendApplication_request::is_recipient_remark_Set() const{
    return m_recipient_remark_isSet;
}

bool OAIChatSendFriendApplication_request::is_recipient_remark_Valid() const{
    return m_recipient_remark_isValid;
}

bool OAIChatSendFriendApplication_request::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_target_user_id_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_verification_message_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_recipient_remark_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIChatSendFriendApplication_request::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_target_user_id_isValid && m_verification_message_isValid && m_recipient_remark_isValid && true;
}

} // namespace OpenAPIChat
