/**
 * 聊天微服务提供的API接口文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIChatAcceptFriendApplication_200_response_data.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIChatHelpers.h"

namespace OpenAPIChat {

OAIChatAcceptFriendApplication_200_response_data::OAIChatAcceptFriendApplication_200_response_data(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIChatAcceptFriendApplication_200_response_data::OAIChatAcceptFriendApplication_200_response_data() {
    this->initializeModel();
}

OAIChatAcceptFriendApplication_200_response_data::~OAIChatAcceptFriendApplication_200_response_data() {}

void OAIChatAcceptFriendApplication_200_response_data::initializeModel() {

    m_create_friend_ship_isSet = false;
    m_create_friend_ship_isValid = false;

    m_friendship_id_isSet = false;
    m_friendship_id_isValid = false;

    m_private_chat_session_id_isSet = false;
    m_private_chat_session_id_isValid = false;

    m_applicant_participant_id_isSet = false;
    m_applicant_participant_id_isValid = false;

    m_target_user_participant_id_isSet = false;
    m_target_user_participant_id_isValid = false;
}

void OAIChatAcceptFriendApplication_200_response_data::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIChatAcceptFriendApplication_200_response_data::fromJsonObject(QJsonObject json) {

    m_create_friend_ship_isValid = ::OpenAPIChat::fromJsonValue(m_create_friend_ship, json[QString("createFriendShip")]);
    m_create_friend_ship_isSet = !json[QString("createFriendShip")].isNull() && m_create_friend_ship_isValid;

    m_friendship_id_isValid = ::OpenAPIChat::fromJsonValue(m_friendship_id, json[QString("friendshipId")]);
    m_friendship_id_isSet = !json[QString("friendshipId")].isNull() && m_friendship_id_isValid;

    m_private_chat_session_id_isValid = ::OpenAPIChat::fromJsonValue(m_private_chat_session_id, json[QString("privateChatSessionId")]);
    m_private_chat_session_id_isSet = !json[QString("privateChatSessionId")].isNull() && m_private_chat_session_id_isValid;

    m_applicant_participant_id_isValid = ::OpenAPIChat::fromJsonValue(m_applicant_participant_id, json[QString("applicantParticipantId")]);
    m_applicant_participant_id_isSet = !json[QString("applicantParticipantId")].isNull() && m_applicant_participant_id_isValid;

    m_target_user_participant_id_isValid = ::OpenAPIChat::fromJsonValue(m_target_user_participant_id, json[QString("targetUserParticipantId")]);
    m_target_user_participant_id_isSet = !json[QString("targetUserParticipantId")].isNull() && m_target_user_participant_id_isValid;
}

QString OAIChatAcceptFriendApplication_200_response_data::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIChatAcceptFriendApplication_200_response_data::asJsonObject() const {
    QJsonObject obj;
    if (m_create_friend_ship_isSet) {
        obj.insert(QString("createFriendShip"), ::OpenAPIChat::toJsonValue(m_create_friend_ship));
    }
    if (m_friendship_id_isSet) {
        obj.insert(QString("friendshipId"), ::OpenAPIChat::toJsonValue(m_friendship_id));
    }
    if (m_private_chat_session_id_isSet) {
        obj.insert(QString("privateChatSessionId"), ::OpenAPIChat::toJsonValue(m_private_chat_session_id));
    }
    if (m_applicant_participant_id_isSet) {
        obj.insert(QString("applicantParticipantId"), ::OpenAPIChat::toJsonValue(m_applicant_participant_id));
    }
    if (m_target_user_participant_id_isSet) {
        obj.insert(QString("targetUserParticipantId"), ::OpenAPIChat::toJsonValue(m_target_user_participant_id));
    }
    return obj;
}

bool OAIChatAcceptFriendApplication_200_response_data::isCreateFriendShip() const {
    return m_create_friend_ship;
}
void OAIChatAcceptFriendApplication_200_response_data::setCreateFriendShip(const bool &create_friend_ship) {
    m_create_friend_ship = create_friend_ship;
    m_create_friend_ship_isSet = true;
}

bool OAIChatAcceptFriendApplication_200_response_data::is_create_friend_ship_Set() const{
    return m_create_friend_ship_isSet;
}

bool OAIChatAcceptFriendApplication_200_response_data::is_create_friend_ship_Valid() const{
    return m_create_friend_ship_isValid;
}

QString OAIChatAcceptFriendApplication_200_response_data::getFriendshipId() const {
    return m_friendship_id;
}
void OAIChatAcceptFriendApplication_200_response_data::setFriendshipId(const QString &friendship_id) {
    m_friendship_id = friendship_id;
    m_friendship_id_isSet = true;
}

bool OAIChatAcceptFriendApplication_200_response_data::is_friendship_id_Set() const{
    return m_friendship_id_isSet;
}

bool OAIChatAcceptFriendApplication_200_response_data::is_friendship_id_Valid() const{
    return m_friendship_id_isValid;
}

QString OAIChatAcceptFriendApplication_200_response_data::getPrivateChatSessionId() const {
    return m_private_chat_session_id;
}
void OAIChatAcceptFriendApplication_200_response_data::setPrivateChatSessionId(const QString &private_chat_session_id) {
    m_private_chat_session_id = private_chat_session_id;
    m_private_chat_session_id_isSet = true;
}

bool OAIChatAcceptFriendApplication_200_response_data::is_private_chat_session_id_Set() const{
    return m_private_chat_session_id_isSet;
}

bool OAIChatAcceptFriendApplication_200_response_data::is_private_chat_session_id_Valid() const{
    return m_private_chat_session_id_isValid;
}

QString OAIChatAcceptFriendApplication_200_response_data::getApplicantParticipantId() const {
    return m_applicant_participant_id;
}
void OAIChatAcceptFriendApplication_200_response_data::setApplicantParticipantId(const QString &applicant_participant_id) {
    m_applicant_participant_id = applicant_participant_id;
    m_applicant_participant_id_isSet = true;
}

bool OAIChatAcceptFriendApplication_200_response_data::is_applicant_participant_id_Set() const{
    return m_applicant_participant_id_isSet;
}

bool OAIChatAcceptFriendApplication_200_response_data::is_applicant_participant_id_Valid() const{
    return m_applicant_participant_id_isValid;
}

QString OAIChatAcceptFriendApplication_200_response_data::getTargetUserParticipantId() const {
    return m_target_user_participant_id;
}
void OAIChatAcceptFriendApplication_200_response_data::setTargetUserParticipantId(const QString &target_user_participant_id) {
    m_target_user_participant_id = target_user_participant_id;
    m_target_user_participant_id_isSet = true;
}

bool OAIChatAcceptFriendApplication_200_response_data::is_target_user_participant_id_Set() const{
    return m_target_user_participant_id_isSet;
}

bool OAIChatAcceptFriendApplication_200_response_data::is_target_user_participant_id_Valid() const{
    return m_target_user_participant_id_isValid;
}

bool OAIChatAcceptFriendApplication_200_response_data::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_create_friend_ship_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_friendship_id_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_private_chat_session_id_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_applicant_participant_id_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_target_user_participant_id_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIChatAcceptFriendApplication_200_response_data::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_create_friend_ship_isValid && true;
}

} // namespace OpenAPIChat
