/**
 * 聊天微服务提供的API接口文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#ifndef OAIChat_OAIChatDefaultApi_H
#define OAIChat_OAIChatDefaultApi_H

#include "OAIChatHelpers.h"
#include "OAIChatHttpRequest.h"
#include "OAIChatServerConfiguration.h"
#include "OAIChatOauth.h"

#include "OAIChatAcceptFriendApplication_200_response.h"
#include "OAIChatAcceptFriendApplication_request.h"
#include "OAIChatRejectFriendApplication_200_response.h"
#include "OAIChatSendFriendApplication_200_response.h"
#include "OAIChatSendFriendApplication_request.h"
#include "OAIChatSendTextMessage_200_response.h"
#include "OAIChatSendTextMessage_request.h"
#include <QString>

#include <QObject>
#include <QByteArray>
#include <QStringList>
#include <QList>
#include <QNetworkAccessManager>

namespace OpenAPIChat {

class OAIChatDefaultApi : public QObject {
    Q_OBJECT

public:
    OAIChatDefaultApi(const int timeOut = 0);
    ~OAIChatDefaultApi();

    void initializeServerConfigs();
    int setDefaultServerValue(int serverIndex,const QString &operation, const QString &variable,const QString &val);
    void setServerIndex(const QString &operation, int serverIndex);
    void setApiKey(const QString &apiKeyName, const QString &apiKey);
    void setBearerToken(const QString &token);
    void setUsername(const QString &username);
    void setPassword(const QString &password);
    void setTimeOut(const int timeOut);
    void setWorkingDirectory(const QString &path);
    void setNetworkAccessManager(QNetworkAccessManager* manager);
    int addServerConfiguration(const QString &operation, const QUrl &url, const QString &description = "", const QMap<QString, OAIChatServerVariable> &variables = QMap<QString, OAIChatServerVariable>());
    void setNewServerForAllOperations(const QUrl &url, const QString &description = "", const QMap<QString, OAIChatServerVariable> &variables =  QMap<QString, OAIChatServerVariable>());
    void setNewServer(const QString &operation, const QUrl &url, const QString &description = "", const QMap<QString, OAIChatServerVariable> &variables =  QMap<QString, OAIChatServerVariable>());
    void addHeaders(const QString &key, const QString &value);
    void enableRequestCompression();
    void enableResponseCompression();
    void abortRequests();
    QString getParamStylePrefix(const QString &style);
    QString getParamStyleSuffix(const QString &style);
    QString getParamStyleDelimiter(const QString &style, const QString &name, bool isExplode);

    /**
    * @param[in]  friend_application_id QString [required]
    * @param[in]  oai_chat_accept_friend_application_request OAIChatAcceptFriendApplication_request [required]
    */
    void acceptFriendApplication(const QString &friend_application_id, const OAIChatAcceptFriendApplication_request &oai_chat_accept_friend_application_request);

    /**
    * @param[in]  friend_application_id QString [required]
    */
    void rejectFriendApplication(const QString &friend_application_id);

    /**
    * @param[in]  oai_chat_send_friend_application_request OAIChatSendFriendApplication_request [required]
    */
    void sendFriendApplication(const OAIChatSendFriendApplication_request &oai_chat_send_friend_application_request);

    /**
    * @param[in]  session_id QString [required]
    * @param[in]  oai_chat_send_text_message_request OAIChatSendTextMessage_request [required]
    */
    void sendTextMessage(const QString &session_id, const OAIChatSendTextMessage_request &oai_chat_send_text_message_request);


private:
    QMap<QString,int> _serverIndices;
    QMap<QString,QList<OAIChatServerConfiguration>> _serverConfigs;
    QMap<QString, QString> _apiKeys;
    QString _bearerToken;
    QString _username;
    QString _password;
    int _timeOut;
    QString _workingDirectory;
    QNetworkAccessManager* _manager;
    QMap<QString, QString> _defaultHeaders;
    bool _isResponseCompressionEnabled;
    bool _isRequestCompressionEnabled;
    OAIChatHttpRequestInput _latestInput;
    OAIChatHttpRequestWorker *_latestWorker;
    QStringList _latestScope;
    OauthCode _authFlow;
    OauthImplicit _implicitFlow;
    OauthCredentials _credentialFlow;
    OauthPassword _passwordFlow;
    int _OauthMethod = 0;

    void acceptFriendApplicationCallback(OAIChatHttpRequestWorker *worker);
    void rejectFriendApplicationCallback(OAIChatHttpRequestWorker *worker);
    void sendFriendApplicationCallback(OAIChatHttpRequestWorker *worker);
    void sendTextMessageCallback(OAIChatHttpRequestWorker *worker);

Q_SIGNALS:

    void acceptFriendApplicationSignal(OAIChatAcceptFriendApplication_200_response summary);
    void rejectFriendApplicationSignal(OAIChatRejectFriendApplication_200_response summary);
    void sendFriendApplicationSignal(OAIChatSendFriendApplication_200_response summary);
    void sendTextMessageSignal(OAIChatSendTextMessage_200_response summary);

    void acceptFriendApplicationSignalFull(OAIChatHttpRequestWorker *worker, OAIChatAcceptFriendApplication_200_response summary);
    void rejectFriendApplicationSignalFull(OAIChatHttpRequestWorker *worker, OAIChatRejectFriendApplication_200_response summary);
    void sendFriendApplicationSignalFull(OAIChatHttpRequestWorker *worker, OAIChatSendFriendApplication_200_response summary);
    void sendTextMessageSignalFull(OAIChatHttpRequestWorker *worker, OAIChatSendTextMessage_200_response summary);

    Q_DECL_DEPRECATED_X("Use acceptFriendApplicationSignalError() instead")
    void acceptFriendApplicationSignalE(OAIChatAcceptFriendApplication_200_response summary, QNetworkReply::NetworkError error_type, QString error_str);
    void acceptFriendApplicationSignalError(OAIChatAcceptFriendApplication_200_response summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use rejectFriendApplicationSignalError() instead")
    void rejectFriendApplicationSignalE(OAIChatRejectFriendApplication_200_response summary, QNetworkReply::NetworkError error_type, QString error_str);
    void rejectFriendApplicationSignalError(OAIChatRejectFriendApplication_200_response summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use sendFriendApplicationSignalError() instead")
    void sendFriendApplicationSignalE(OAIChatSendFriendApplication_200_response summary, QNetworkReply::NetworkError error_type, QString error_str);
    void sendFriendApplicationSignalError(OAIChatSendFriendApplication_200_response summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use sendTextMessageSignalError() instead")
    void sendTextMessageSignalE(OAIChatSendTextMessage_200_response summary, QNetworkReply::NetworkError error_type, QString error_str);
    void sendTextMessageSignalError(OAIChatSendTextMessage_200_response summary, QNetworkReply::NetworkError error_type, const QString &error_str);

    Q_DECL_DEPRECATED_X("Use acceptFriendApplicationSignalErrorFull() instead")
    void acceptFriendApplicationSignalEFull(OAIChatHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void acceptFriendApplicationSignalErrorFull(OAIChatHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use rejectFriendApplicationSignalErrorFull() instead")
    void rejectFriendApplicationSignalEFull(OAIChatHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void rejectFriendApplicationSignalErrorFull(OAIChatHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use sendFriendApplicationSignalErrorFull() instead")
    void sendFriendApplicationSignalEFull(OAIChatHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void sendFriendApplicationSignalErrorFull(OAIChatHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use sendTextMessageSignalErrorFull() instead")
    void sendTextMessageSignalEFull(OAIChatHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void sendTextMessageSignalErrorFull(OAIChatHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);

    void abortRequestsSignal();
    void allPendingRequestsCompleted();

public Q_SLOTS:
    void tokenAvailable();
};

} // namespace OpenAPIChat
#endif
