/**
 * 聊天微服务提供的API接口文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIChatSendTextMessage_request.h
 *
 * 
 */

#ifndef OAIChatSendTextMessage_request_H
#define OAIChatSendTextMessage_request_H

#include <QJsonObject>

#include <QString>

#include "OAIChatEnum.h"
#include "OAIChatObject.h"

namespace OpenAPIChat {

class OAIChatSendTextMessage_request : public OAIChatObject {
public:
    OAIChatSendTextMessage_request();
    OAIChatSendTextMessage_request(QString json);
    ~OAIChatSendTextMessage_request() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getContent() const;
    void setContent(const QString &content);
    bool is_content_Set() const;
    bool is_content_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString m_content;
    bool m_content_isSet;
    bool m_content_isValid;
};

} // namespace OpenAPIChat

Q_DECLARE_METATYPE(OpenAPIChat::OAIChatSendTextMessage_request)

#endif // OAIChatSendTextMessage_request_H
