/**
 * 聊天微服务提供的API接口文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIChatSendFriendApplication_request.h
 *
 * 
 */

#ifndef OAIChatSendFriendApplication_request_H
#define OAIChatSendFriendApplication_request_H

#include <QJsonObject>

#include <QString>

#include "OAIChatEnum.h"
#include "OAIChatObject.h"

namespace OpenAPIChat {

class OAIChatSendFriendApplication_request : public OAIChatObject {
public:
    OAIChatSendFriendApplication_request();
    OAIChatSendFriendApplication_request(QString json);
    ~OAIChatSendFriendApplication_request() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getTargetUserId() const;
    void setTargetUserId(const QString &target_user_id);
    bool is_target_user_id_Set() const;
    bool is_target_user_id_Valid() const;

    QString getVerificationMessage() const;
    void setVerificationMessage(const QString &verification_message);
    bool is_verification_message_Set() const;
    bool is_verification_message_Valid() const;

    QString getRecipientRemark() const;
    void setRecipientRemark(const QString &recipient_remark);
    bool is_recipient_remark_Set() const;
    bool is_recipient_remark_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString m_target_user_id;
    bool m_target_user_id_isSet;
    bool m_target_user_id_isValid;

    QString m_verification_message;
    bool m_verification_message_isSet;
    bool m_verification_message_isValid;

    QString m_recipient_remark;
    bool m_recipient_remark_isSet;
    bool m_recipient_remark_isValid;
};

} // namespace OpenAPIChat

Q_DECLARE_METATYPE(OpenAPIChat::OAIChatSendFriendApplication_request)

#endif // OAIChatSendFriendApplication_request_H
