/**
 * 聊天微服务提供的API接口文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIChatAcceptFriendApplication_200_response_data.h
 *
 * 
 */

#ifndef OAIChatAcceptFriendApplication_200_response_data_H
#define OAIChatAcceptFriendApplication_200_response_data_H

#include <QJsonObject>

#include <QString>

#include "OAIChatEnum.h"
#include "OAIChatObject.h"

namespace OpenAPIChat {

class OAIChatAcceptFriendApplication_200_response_data : public OAIChatObject {
public:
    OAIChatAcceptFriendApplication_200_response_data();
    OAIChatAcceptFriendApplication_200_response_data(QString json);
    ~OAIChatAcceptFriendApplication_200_response_data() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    bool isCreateFriendShip() const;
    void setCreateFriendShip(const bool &create_friend_ship);
    bool is_create_friend_ship_Set() const;
    bool is_create_friend_ship_Valid() const;

    QString getFriendshipId() const;
    void setFriendshipId(const QString &friendship_id);
    bool is_friendship_id_Set() const;
    bool is_friendship_id_Valid() const;

    QString getPrivateChatSessionId() const;
    void setPrivateChatSessionId(const QString &private_chat_session_id);
    bool is_private_chat_session_id_Set() const;
    bool is_private_chat_session_id_Valid() const;

    QString getApplicantParticipantId() const;
    void setApplicantParticipantId(const QString &applicant_participant_id);
    bool is_applicant_participant_id_Set() const;
    bool is_applicant_participant_id_Valid() const;

    QString getTargetUserParticipantId() const;
    void setTargetUserParticipantId(const QString &target_user_participant_id);
    bool is_target_user_participant_id_Set() const;
    bool is_target_user_participant_id_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    bool m_create_friend_ship;
    bool m_create_friend_ship_isSet;
    bool m_create_friend_ship_isValid;

    QString m_friendship_id;
    bool m_friendship_id_isSet;
    bool m_friendship_id_isValid;

    QString m_private_chat_session_id;
    bool m_private_chat_session_id_isSet;
    bool m_private_chat_session_id_isValid;

    QString m_applicant_participant_id;
    bool m_applicant_participant_id_isSet;
    bool m_applicant_participant_id_isValid;

    QString m_target_user_participant_id;
    bool m_target_user_participant_id_isSet;
    bool m_target_user_participant_id_isValid;
};

} // namespace OpenAPIChat

Q_DECLARE_METATYPE(OpenAPIChat::OAIChatAcceptFriendApplication_200_response_data)

#endif // OAIChatAcceptFriendApplication_200_response_data_H
