/**
 * 聊天微服务提供的API接口文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIChatSendTextMessage_200_response_data.h
 *
 * 
 */

#ifndef OAIChatSendTextMessage_200_response_data_H
#define OAIChatSendTextMessage_200_response_data_H

#include <QJsonObject>

#include <QString>

#include "OAIChatEnum.h"
#include "OAIChatObject.h"

namespace OpenAPIChat {

class OAIChatSendTextMessage_200_response_data : public OAIChatObject {
public:
    OAIChatSendTextMessage_200_response_data();
    OAIChatSendTextMessage_200_response_data(QString json);
    ~OAIChatSendTextMessage_200_response_data() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getMessageId() const;
    void setMessageId(const QString &message_id);
    bool is_message_id_Set() const;
    bool is_message_id_Valid() const;

    qint64 getSequence() const;
    void setSequence(const qint64 &sequence);
    bool is_sequence_Set() const;
    bool is_sequence_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString m_message_id;
    bool m_message_id_isSet;
    bool m_message_id_isValid;

    qint64 m_sequence;
    bool m_sequence_isSet;
    bool m_sequence_isValid;
};

} // namespace OpenAPIChat

Q_DECLARE_METATYPE(OpenAPIChat::OAIChatSendTextMessage_200_response_data)

#endif // OAIChatSendTextMessage_200_response_data_H
