/**
 * 聊天微服务提供的API接口文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIChatSendFriendApplication_200_response_data.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIChatHelpers.h"

namespace OpenAPIChat {

OAIChatSendFriendApplication_200_response_data::OAIChatSendFriendApplication_200_response_data(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIChatSendFriendApplication_200_response_data::OAIChatSendFriendApplication_200_response_data() {
    this->initializeModel();
}

OAIChatSendFriendApplication_200_response_data::~OAIChatSendFriendApplication_200_response_data() {}

void OAIChatSendFriendApplication_200_response_data::initializeModel() {

    m_friend_application_id_isSet = false;
    m_friend_application_id_isValid = false;
}

void OAIChatSendFriendApplication_200_response_data::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIChatSendFriendApplication_200_response_data::fromJsonObject(QJsonObject json) {

    m_friend_application_id_isValid = ::OpenAPIChat::fromJsonValue(m_friend_application_id, json[QString("friendApplicationId")]);
    m_friend_application_id_isSet = !json[QString("friendApplicationId")].isNull() && m_friend_application_id_isValid;
}

QString OAIChatSendFriendApplication_200_response_data::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIChatSendFriendApplication_200_response_data::asJsonObject() const {
    QJsonObject obj;
    if (m_friend_application_id_isSet) {
        obj.insert(QString("friendApplicationId"), ::OpenAPIChat::toJsonValue(m_friend_application_id));
    }
    return obj;
}

QString OAIChatSendFriendApplication_200_response_data::getFriendApplicationId() const {
    return m_friend_application_id;
}
void OAIChatSendFriendApplication_200_response_data::setFriendApplicationId(const QString &friend_application_id) {
    m_friend_application_id = friend_application_id;
    m_friend_application_id_isSet = true;
}

bool OAIChatSendFriendApplication_200_response_data::is_friend_application_id_Set() const{
    return m_friend_application_id_isSet;
}

bool OAIChatSendFriendApplication_200_response_data::is_friend_application_id_Valid() const{
    return m_friend_application_id_isValid;
}

bool OAIChatSendFriendApplication_200_response_data::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_friend_application_id_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIChatSendFriendApplication_200_response_data::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPIChat
