openapi: 3.0.0
info:
  title: 鉴权认证微服务提供的API接口文档
  version: 1.0.0

servers:
  - url: http://localhost:8080/api

# 定义认证方式
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 网关验证Token后会在Header中注入 X-User-Id

  # 定义网关注入的 Header 参数（可复用）
  parameters:
    XUserId:
      name: X-User-Id
      in: header
      required: true
      schema:
        type: string
      description: 网关从Token解析后注入的用户ID（客户端无需传递）

paths:
  /auth/login:
    post:
      operationId: login
      description: 用户登录，成功后返回userId 和 token
      # 登录时不需要认证，客户端无需传递token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - account
                - password
              properties:
                account:
                  description: 用户ID或者手机号
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                required:
                  - success
                properties:
                  success:
                    type: boolean
                  data:
                    type: object
                    required:
                      - token
                      - userId
                      - phone
                      - nickname
                      - description
                      - avatarFileId
                    properties:
                      token:
                        type: string
                        description: JWT Token，后续请求放在 Authorization 头
                      userId:
                        type: string
                        description: 用户ID
                      phone:
                        type: string
                        description: 用户手机号
                      nickname:
                        type: string
                        description: 用户昵称
                      description:
                        type: string
                        description: 用户个性签名
                      avatarFileId:
                        type: string
                        description: 头像文件ID
                  errCode:
                    type: string
                    description: 错误码
                    enum:
                      - "ACCOUNT_PASSWORD_NOT_MATCH"
                      - "UNKNOWN_ERROR"
                  errMsg:
                    type: string
                    description: 错误信息



