/**
 * 用户微服务提供的API接口文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIUserRegisterUser_request.h
 *
 * 
 */

#ifndef OAIUserRegisterUser_request_H
#define OAIUserRegisterUser_request_H

#include <QJsonObject>

#include <QString>

#include "OAIUserEnum.h"
#include "OAIUserObject.h"

namespace OpenAPIUser {

class OAIUserRegisterUser_request : public OAIUserObject {
public:
    OAIUserRegisterUser_request();
    OAIUserRegisterUser_request(QString json);
    ~OAIUserRegisterUser_request() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getNickname() const;
    void setNickname(const QString &nickname);
    bool is_nickname_Set() const;
    bool is_nickname_Valid() const;

    QString getAvatar() const;
    void setAvatar(const QString &avatar);
    bool is_avatar_Set() const;
    bool is_avatar_Valid() const;

    QString getPhone() const;
    void setPhone(const QString &phone);
    bool is_phone_Set() const;
    bool is_phone_Valid() const;

    QString getPassword() const;
    void setPassword(const QString &password);
    bool is_password_Set() const;
    bool is_password_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString m_nickname;
    bool m_nickname_isSet;
    bool m_nickname_isValid;

    QString m_avatar;
    bool m_avatar_isSet;
    bool m_avatar_isValid;

    QString m_phone;
    bool m_phone_isSet;
    bool m_phone_isValid;

    QString m_password;
    bool m_password_isSet;
    bool m_password_isValid;
};

} // namespace OpenAPIUser

Q_DECLARE_METATYPE(OpenAPIUser::OAIUserRegisterUser_request)

#endif // OAIUserRegisterUser_request_H
