/**
 * 用户微服务提供的API接口文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIUserSearchUser_200_response_data.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIUserHelpers.h"

namespace OpenAPIUser {

OAIUserSearchUser_200_response_data::OAIUserSearchUser_200_response_data(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIUserSearchUser_200_response_data::OAIUserSearchUser_200_response_data() {
    this->initializeModel();
}

OAIUserSearchUser_200_response_data::~OAIUserSearchUser_200_response_data() {}

void OAIUserSearchUser_200_response_data::initializeModel() {

    m_user_id_isSet = false;
    m_user_id_isValid = false;

    m_nickname_isSet = false;
    m_nickname_isValid = false;

    m_avatar_file_id_isSet = false;
    m_avatar_file_id_isValid = false;

    m_phone_isSet = false;
    m_phone_isValid = false;

    m_description_isSet = false;
    m_description_isValid = false;
}

void OAIUserSearchUser_200_response_data::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIUserSearchUser_200_response_data::fromJsonObject(QJsonObject json) {

    m_user_id_isValid = ::OpenAPIUser::fromJsonValue(m_user_id, json[QString("userId")]);
    m_user_id_isSet = !json[QString("userId")].isNull() && m_user_id_isValid;

    m_nickname_isValid = ::OpenAPIUser::fromJsonValue(m_nickname, json[QString("nickname")]);
    m_nickname_isSet = !json[QString("nickname")].isNull() && m_nickname_isValid;

    m_avatar_file_id_isValid = ::OpenAPIUser::fromJsonValue(m_avatar_file_id, json[QString("avatarFileId")]);
    m_avatar_file_id_isSet = !json[QString("avatarFileId")].isNull() && m_avatar_file_id_isValid;

    m_phone_isValid = ::OpenAPIUser::fromJsonValue(m_phone, json[QString("phone")]);
    m_phone_isSet = !json[QString("phone")].isNull() && m_phone_isValid;

    m_description_isValid = ::OpenAPIUser::fromJsonValue(m_description, json[QString("description")]);
    m_description_isSet = !json[QString("description")].isNull() && m_description_isValid;
}

QString OAIUserSearchUser_200_response_data::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIUserSearchUser_200_response_data::asJsonObject() const {
    QJsonObject obj;
    if (m_user_id_isSet) {
        obj.insert(QString("userId"), ::OpenAPIUser::toJsonValue(m_user_id));
    }
    if (m_nickname_isSet) {
        obj.insert(QString("nickname"), ::OpenAPIUser::toJsonValue(m_nickname));
    }
    if (m_avatar_file_id_isSet) {
        obj.insert(QString("avatarFileId"), ::OpenAPIUser::toJsonValue(m_avatar_file_id));
    }
    if (m_phone_isSet) {
        obj.insert(QString("phone"), ::OpenAPIUser::toJsonValue(m_phone));
    }
    if (m_description_isSet) {
        obj.insert(QString("description"), ::OpenAPIUser::toJsonValue(m_description));
    }
    return obj;
}

QString OAIUserSearchUser_200_response_data::getUserId() const {
    return m_user_id;
}
void OAIUserSearchUser_200_response_data::setUserId(const QString &user_id) {
    m_user_id = user_id;
    m_user_id_isSet = true;
}

bool OAIUserSearchUser_200_response_data::is_user_id_Set() const{
    return m_user_id_isSet;
}

bool OAIUserSearchUser_200_response_data::is_user_id_Valid() const{
    return m_user_id_isValid;
}

QString OAIUserSearchUser_200_response_data::getNickname() const {
    return m_nickname;
}
void OAIUserSearchUser_200_response_data::setNickname(const QString &nickname) {
    m_nickname = nickname;
    m_nickname_isSet = true;
}

bool OAIUserSearchUser_200_response_data::is_nickname_Set() const{
    return m_nickname_isSet;
}

bool OAIUserSearchUser_200_response_data::is_nickname_Valid() const{
    return m_nickname_isValid;
}

QString OAIUserSearchUser_200_response_data::getAvatarFileId() const {
    return m_avatar_file_id;
}
void OAIUserSearchUser_200_response_data::setAvatarFileId(const QString &avatar_file_id) {
    m_avatar_file_id = avatar_file_id;
    m_avatar_file_id_isSet = true;
}

bool OAIUserSearchUser_200_response_data::is_avatar_file_id_Set() const{
    return m_avatar_file_id_isSet;
}

bool OAIUserSearchUser_200_response_data::is_avatar_file_id_Valid() const{
    return m_avatar_file_id_isValid;
}

QString OAIUserSearchUser_200_response_data::getPhone() const {
    return m_phone;
}
void OAIUserSearchUser_200_response_data::setPhone(const QString &phone) {
    m_phone = phone;
    m_phone_isSet = true;
}

bool OAIUserSearchUser_200_response_data::is_phone_Set() const{
    return m_phone_isSet;
}

bool OAIUserSearchUser_200_response_data::is_phone_Valid() const{
    return m_phone_isValid;
}

QString OAIUserSearchUser_200_response_data::getDescription() const {
    return m_description;
}
void OAIUserSearchUser_200_response_data::setDescription(const QString &description) {
    m_description = description;
    m_description_isSet = true;
}

bool OAIUserSearchUser_200_response_data::is_description_Set() const{
    return m_description_isSet;
}

bool OAIUserSearchUser_200_response_data::is_description_Valid() const{
    return m_description_isValid;
}

bool OAIUserSearchUser_200_response_data::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_user_id_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_nickname_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_avatar_file_id_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_phone_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_description_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIUserSearchUser_200_response_data::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_user_id_isValid && m_nickname_isValid && m_avatar_file_id_isValid && m_phone_isValid && m_description_isValid && true;
}

} // namespace OpenAPIUser
