/**
 * 用户微服务提供的API接口文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIUserSearchUser_200_response.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIUserHelpers.h"

namespace OpenAPIUser {

OAIUserSearchUser_200_response::OAIUserSearchUser_200_response(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIUserSearchUser_200_response::OAIUserSearchUser_200_response() {
    this->initializeModel();
}

OAIUserSearchUser_200_response::~OAIUserSearchUser_200_response() {}

void OAIUserSearchUser_200_response::initializeModel() {

    m_success_isSet = false;
    m_success_isValid = false;

    m_data_isSet = false;
    m_data_isValid = false;

    m_err_code_isSet = false;
    m_err_code_isValid = false;

    m_err_msg_isSet = false;
    m_err_msg_isValid = false;
}

void OAIUserSearchUser_200_response::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIUserSearchUser_200_response::fromJsonObject(QJsonObject json) {

    m_success_isValid = ::OpenAPIUser::fromJsonValue(m_success, json[QString("success")]);
    m_success_isSet = !json[QString("success")].isNull() && m_success_isValid;

    m_data_isValid = ::OpenAPIUser::fromJsonValue(m_data, json[QString("data")]);
    m_data_isSet = !json[QString("data")].isNull() && m_data_isValid;

    m_err_code_isValid = ::OpenAPIUser::fromJsonValue(m_err_code, json[QString("errCode")]);
    m_err_code_isSet = !json[QString("errCode")].isNull() && m_err_code_isValid;

    m_err_msg_isValid = ::OpenAPIUser::fromJsonValue(m_err_msg, json[QString("errMsg")]);
    m_err_msg_isSet = !json[QString("errMsg")].isNull() && m_err_msg_isValid;
}

QString OAIUserSearchUser_200_response::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIUserSearchUser_200_response::asJsonObject() const {
    QJsonObject obj;
    if (m_success_isSet) {
        obj.insert(QString("success"), ::OpenAPIUser::toJsonValue(m_success));
    }
    if (m_data.isSet()) {
        obj.insert(QString("data"), ::OpenAPIUser::toJsonValue(m_data));
    }
    if (m_err_code_isSet) {
        obj.insert(QString("errCode"), ::OpenAPIUser::toJsonValue(m_err_code));
    }
    if (m_err_msg_isSet) {
        obj.insert(QString("errMsg"), ::OpenAPIUser::toJsonValue(m_err_msg));
    }
    return obj;
}

bool OAIUserSearchUser_200_response::isSuccess() const {
    return m_success;
}
void OAIUserSearchUser_200_response::setSuccess(const bool &success) {
    m_success = success;
    m_success_isSet = true;
}

bool OAIUserSearchUser_200_response::is_success_Set() const{
    return m_success_isSet;
}

bool OAIUserSearchUser_200_response::is_success_Valid() const{
    return m_success_isValid;
}

OAIUserSearchUser_200_response_data OAIUserSearchUser_200_response::getData() const {
    return m_data;
}
void OAIUserSearchUser_200_response::setData(const OAIUserSearchUser_200_response_data &data) {
    m_data = data;
    m_data_isSet = true;
}

bool OAIUserSearchUser_200_response::is_data_Set() const{
    return m_data_isSet;
}

bool OAIUserSearchUser_200_response::is_data_Valid() const{
    return m_data_isValid;
}

QString OAIUserSearchUser_200_response::getErrCode() const {
    return m_err_code;
}
void OAIUserSearchUser_200_response::setErrCode(const QString &err_code) {
    m_err_code = err_code;
    m_err_code_isSet = true;
}

bool OAIUserSearchUser_200_response::is_err_code_Set() const{
    return m_err_code_isSet;
}

bool OAIUserSearchUser_200_response::is_err_code_Valid() const{
    return m_err_code_isValid;
}

QString OAIUserSearchUser_200_response::getErrMsg() const {
    return m_err_msg;
}
void OAIUserSearchUser_200_response::setErrMsg(const QString &err_msg) {
    m_err_msg = err_msg;
    m_err_msg_isSet = true;
}

bool OAIUserSearchUser_200_response::is_err_msg_Set() const{
    return m_err_msg_isSet;
}

bool OAIUserSearchUser_200_response::is_err_msg_Valid() const{
    return m_err_msg_isValid;
}

bool OAIUserSearchUser_200_response::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_success_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_data.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (m_err_code_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_err_msg_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIUserSearchUser_200_response::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_success_isValid && true;
}

} // namespace OpenAPIUser
