/**
 * 用户微服务提供的API接口文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIUserRegisterUser_200_response_data.h
 *
 * 
 */

#ifndef OAIUserRegisterUser_200_response_data_H
#define OAIUserRegisterUser_200_response_data_H

#include <QJsonObject>


#include "OAIUserEnum.h"
#include "OAIUserObject.h"

namespace OpenAPIUser {

class OAIUserRegisterUser_200_response_data : public OAIUserObject {
public:
    OAIUserRegisterUser_200_response_data();
    OAIUserRegisterUser_200_response_data(QString json);
    ~OAIUserRegisterUser_200_response_data() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    qint32 getUserId() const;
    void setUserId(const qint32 &user_id);
    bool is_user_id_Set() const;
    bool is_user_id_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    qint32 m_user_id;
    bool m_user_id_isSet;
    bool m_user_id_isValid;
};

} // namespace OpenAPIUser

Q_DECLARE_METATYPE(OpenAPIUser::OAIUserRegisterUser_200_response_data)

#endif // OAIUserRegisterUser_200_response_data_H
