/**
 * 用户微服务提供的API接口文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIUserRegisterUser_200_response_data.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIUserHelpers.h"

namespace OpenAPIUser {

OAIUserRegisterUser_200_response_data::OAIUserRegisterUser_200_response_data(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIUserRegisterUser_200_response_data::OAIUserRegisterUser_200_response_data() {
    this->initializeModel();
}

OAIUserRegisterUser_200_response_data::~OAIUserRegisterUser_200_response_data() {}

void OAIUserRegisterUser_200_response_data::initializeModel() {

    m_user_id_isSet = false;
    m_user_id_isValid = false;
}

void OAIUserRegisterUser_200_response_data::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIUserRegisterUser_200_response_data::fromJsonObject(QJsonObject json) {

    m_user_id_isValid = ::OpenAPIUser::fromJsonValue(m_user_id, json[QString("userId")]);
    m_user_id_isSet = !json[QString("userId")].isNull() && m_user_id_isValid;
}

QString OAIUserRegisterUser_200_response_data::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIUserRegisterUser_200_response_data::asJsonObject() const {
    QJsonObject obj;
    if (m_user_id_isSet) {
        obj.insert(QString("userId"), ::OpenAPIUser::toJsonValue(m_user_id));
    }
    return obj;
}

qint32 OAIUserRegisterUser_200_response_data::getUserId() const {
    return m_user_id;
}
void OAIUserRegisterUser_200_response_data::setUserId(const qint32 &user_id) {
    m_user_id = user_id;
    m_user_id_isSet = true;
}

bool OAIUserRegisterUser_200_response_data::is_user_id_Set() const{
    return m_user_id_isSet;
}

bool OAIUserRegisterUser_200_response_data::is_user_id_Valid() const{
    return m_user_id_isValid;
}

bool OAIUserRegisterUser_200_response_data::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_user_id_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIUserRegisterUser_200_response_data::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPIUser
