/**
 * 用户微服务提供的API接口文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIUserRegisterUser_request.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIUserHelpers.h"

namespace OpenAPIUser {

OAIUserRegisterUser_request::OAIUserRegisterUser_request(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIUserRegisterUser_request::OAIUserRegisterUser_request() {
    this->initializeModel();
}

OAIUserRegisterUser_request::~OAIUserRegisterUser_request() {}

void OAIUserRegisterUser_request::initializeModel() {

    m_nickname_isSet = false;
    m_nickname_isValid = false;

    m_avatar_isSet = false;
    m_avatar_isValid = false;

    m_phone_isSet = false;
    m_phone_isValid = false;

    m_password_isSet = false;
    m_password_isValid = false;
}

void OAIUserRegisterUser_request::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIUserRegisterUser_request::fromJsonObject(QJsonObject json) {

    m_nickname_isValid = ::OpenAPIUser::fromJsonValue(m_nickname, json[QString("nickname")]);
    m_nickname_isSet = !json[QString("nickname")].isNull() && m_nickname_isValid;

    m_avatar_isValid = ::OpenAPIUser::fromJsonValue(m_avatar, json[QString("avatar")]);
    m_avatar_isSet = !json[QString("avatar")].isNull() && m_avatar_isValid;

    m_phone_isValid = ::OpenAPIUser::fromJsonValue(m_phone, json[QString("phone")]);
    m_phone_isSet = !json[QString("phone")].isNull() && m_phone_isValid;

    m_password_isValid = ::OpenAPIUser::fromJsonValue(m_password, json[QString("password")]);
    m_password_isSet = !json[QString("password")].isNull() && m_password_isValid;
}

QString OAIUserRegisterUser_request::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIUserRegisterUser_request::asJsonObject() const {
    QJsonObject obj;
    if (m_nickname_isSet) {
        obj.insert(QString("nickname"), ::OpenAPIUser::toJsonValue(m_nickname));
    }
    if (m_avatar_isSet) {
        obj.insert(QString("avatar"), ::OpenAPIUser::toJsonValue(m_avatar));
    }
    if (m_phone_isSet) {
        obj.insert(QString("phone"), ::OpenAPIUser::toJsonValue(m_phone));
    }
    if (m_password_isSet) {
        obj.insert(QString("password"), ::OpenAPIUser::toJsonValue(m_password));
    }
    return obj;
}

QString OAIUserRegisterUser_request::getNickname() const {
    return m_nickname;
}
void OAIUserRegisterUser_request::setNickname(const QString &nickname) {
    m_nickname = nickname;
    m_nickname_isSet = true;
}

bool OAIUserRegisterUser_request::is_nickname_Set() const{
    return m_nickname_isSet;
}

bool OAIUserRegisterUser_request::is_nickname_Valid() const{
    return m_nickname_isValid;
}

QString OAIUserRegisterUser_request::getAvatar() const {
    return m_avatar;
}
void OAIUserRegisterUser_request::setAvatar(const QString &avatar) {
    m_avatar = avatar;
    m_avatar_isSet = true;
}

bool OAIUserRegisterUser_request::is_avatar_Set() const{
    return m_avatar_isSet;
}

bool OAIUserRegisterUser_request::is_avatar_Valid() const{
    return m_avatar_isValid;
}

QString OAIUserRegisterUser_request::getPhone() const {
    return m_phone;
}
void OAIUserRegisterUser_request::setPhone(const QString &phone) {
    m_phone = phone;
    m_phone_isSet = true;
}

bool OAIUserRegisterUser_request::is_phone_Set() const{
    return m_phone_isSet;
}

bool OAIUserRegisterUser_request::is_phone_Valid() const{
    return m_phone_isValid;
}

QString OAIUserRegisterUser_request::getPassword() const {
    return m_password;
}
void OAIUserRegisterUser_request::setPassword(const QString &password) {
    m_password = password;
    m_password_isSet = true;
}

bool OAIUserRegisterUser_request::is_password_Set() const{
    return m_password_isSet;
}

bool OAIUserRegisterUser_request::is_password_Valid() const{
    return m_password_isValid;
}

bool OAIUserRegisterUser_request::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_nickname_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_avatar_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_phone_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_password_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIUserRegisterUser_request::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_nickname_isValid && m_avatar_isValid && m_phone_isValid && m_password_isValid && true;
}

} // namespace OpenAPIUser
