/**
 * 用户微服务提供的API接口文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#ifndef OAIUser_OAIUserDefaultApi_H
#define OAIUser_OAIUserDefaultApi_H

#include "OAIUserHelpers.h"
#include "OAIUserHttpRequest.h"
#include "OAIUserServerConfiguration.h"
#include "OAIUserOauth.h"

#include "OAIUserRegisterUser_200_response.h"
#include "OAIUserRegisterUser_request.h"
#include "OAIUserSearchUser_200_response.h"
#include <QString>

#include <QObject>
#include <QByteArray>
#include <QStringList>
#include <QList>
#include <QNetworkAccessManager>

namespace OpenAPIUser {

class OAIUserDefaultApi : public QObject {
    Q_OBJECT

public:
    OAIUserDefaultApi(const int timeOut = 0);
    ~OAIUserDefaultApi();

    void initializeServerConfigs();
    int setDefaultServerValue(int serverIndex,const QString &operation, const QString &variable,const QString &val);
    void setServerIndex(const QString &operation, int serverIndex);
    void setApiKey(const QString &apiKeyName, const QString &apiKey);
    void setBearerToken(const QString &token);
    void setUsername(const QString &username);
    void setPassword(const QString &password);
    void setTimeOut(const int timeOut);
    void setWorkingDirectory(const QString &path);
    void setNetworkAccessManager(QNetworkAccessManager* manager);
    int addServerConfiguration(const QString &operation, const QUrl &url, const QString &description = "", const QMap<QString, OAIUserServerVariable> &variables = QMap<QString, OAIUserServerVariable>());
    void setNewServerForAllOperations(const QUrl &url, const QString &description = "", const QMap<QString, OAIUserServerVariable> &variables =  QMap<QString, OAIUserServerVariable>());
    void setNewServer(const QString &operation, const QUrl &url, const QString &description = "", const QMap<QString, OAIUserServerVariable> &variables =  QMap<QString, OAIUserServerVariable>());
    void addHeaders(const QString &key, const QString &value);
    void enableRequestCompression();
    void enableResponseCompression();
    void abortRequests();
    QString getParamStylePrefix(const QString &style);
    QString getParamStyleSuffix(const QString &style);
    QString getParamStyleDelimiter(const QString &style, const QString &name, bool isExplode);

    /**
    * @param[in]  oai_user_register_user_request OAIUserRegisterUser_request [required]
    */
    void registerUser(const OAIUserRegisterUser_request &oai_user_register_user_request);

    /**
    * @param[in]  keyword QString [required]
    */
    void searchUser(const QString &keyword);


private:
    QMap<QString,int> _serverIndices;
    QMap<QString,QList<OAIUserServerConfiguration>> _serverConfigs;
    QMap<QString, QString> _apiKeys;
    QString _bearerToken;
    QString _username;
    QString _password;
    int _timeOut;
    QString _workingDirectory;
    QNetworkAccessManager* _manager;
    QMap<QString, QString> _defaultHeaders;
    bool _isResponseCompressionEnabled;
    bool _isRequestCompressionEnabled;
    OAIUserHttpRequestInput _latestInput;
    OAIUserHttpRequestWorker *_latestWorker;
    QStringList _latestScope;
    OauthCode _authFlow;
    OauthImplicit _implicitFlow;
    OauthCredentials _credentialFlow;
    OauthPassword _passwordFlow;
    int _OauthMethod = 0;

    void registerUserCallback(OAIUserHttpRequestWorker *worker);
    void searchUserCallback(OAIUserHttpRequestWorker *worker);

Q_SIGNALS:

    void registerUserSignal(OAIUserRegisterUser_200_response summary);
    void searchUserSignal(OAIUserSearchUser_200_response summary);

    void registerUserSignalFull(OAIUserHttpRequestWorker *worker, OAIUserRegisterUser_200_response summary);
    void searchUserSignalFull(OAIUserHttpRequestWorker *worker, OAIUserSearchUser_200_response summary);

    Q_DECL_DEPRECATED_X("Use registerUserSignalError() instead")
    void registerUserSignalE(OAIUserRegisterUser_200_response summary, QNetworkReply::NetworkError error_type, QString error_str);
    void registerUserSignalError(OAIUserRegisterUser_200_response summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use searchUserSignalError() instead")
    void searchUserSignalE(OAIUserSearchUser_200_response summary, QNetworkReply::NetworkError error_type, QString error_str);
    void searchUserSignalError(OAIUserSearchUser_200_response summary, QNetworkReply::NetworkError error_type, const QString &error_str);

    Q_DECL_DEPRECATED_X("Use registerUserSignalErrorFull() instead")
    void registerUserSignalEFull(OAIUserHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void registerUserSignalErrorFull(OAIUserHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    Q_DECL_DEPRECATED_X("Use searchUserSignalErrorFull() instead")
    void searchUserSignalEFull(OAIUserHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void searchUserSignalErrorFull(OAIUserHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);

    void abortRequestsSignal();
    void allPendingRequestsCompleted();

public Q_SLOTS:
    void tokenAvailable();
};

} // namespace OpenAPIUser
#endif
