/**
 * 用户微服务提供的API接口文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#ifndef OAIUser_ENUM_H
#define OAIUser_ENUM_H

#include <QJsonValue>
#include <QMetaType>
#include <QString>

namespace OpenAPIUser {

class OAIUserEnum {
public:
    OAIUserEnum() {}

    OAIUserEnum(QString jsonString) {
        fromJson(jsonString);
    }

    virtual ~OAIUserEnum() {}

    virtual QJsonValue asJsonValue() const {
        return QJsonValue(jstr);
    }

    virtual QString asJson() const {
        return jstr;
    }

    virtual void fromJson(QString jsonString) {
        jstr = jsonString;
    }

    virtual void fromJsonValue(QJsonValue jval) {
        jstr = jval.toString();
    }

    virtual bool isSet() const {
        return false;
    }

    virtual bool isValid() const {
        return true;
    }

private:
    QString jstr;
};

} // namespace OpenAPIUser

Q_DECLARE_METATYPE(OpenAPIUser::OAIUserEnum)

#endif // OAIUser_ENUM_H
